server:
  port: 8088
batch:
  system:
    enabled: true
    flag: DIRECT
#spring:
#  rabbitmq:
#    host: 192.168.1.150
#    port: 5672
#    password: guest
  jmx:
    enabled: false

fdfs:
  so-timeout: 100000
  connect-timeout: 60000
  tracker-list:
    - 192.168.43.150:22122