server:
  port: 8077

spring:
  application:
    name: sub-system
  rabbitmq:
    host: 192.168.123.29
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    template:
      mandatory: true

