server:
  port: 8077

spring:
  application:
    name: sub-system
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    template:
      mandatory: true

