server:
  port: 8089

spring:
  application:
    name: middle-datasource
  rabbitmq:
    host: 192.168.123.29
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    template:
      mandatory: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bank?characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root